services:
  - type: web
    name: vibrafit
    env: python
    region: ohio
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vibrafit.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        fromDatabase:
          name: vibrafit-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: vibrafit-backend.onrender.com
