# Generated by Django 5.2 on 2025-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_is_onboarded_user_name_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePictureUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
